### ISSUE TITLE
Codemod runs on instances of Map and WeakMap

### ISSUE THREAD

**Issue by tylerbecks** [seanjohnson08/ember-getset-util-codemod#7]
This codemod will incorrectly transform the `.set` and `.get` calls of a native JS Map and WeakMap.

For example:
```
const fooMap = new Map();
fooMap.set('bar', 'baz');
```
will be incorrectly changed to:
```
const fooMap = new Map();
set(fooMap, 'bar', 'baz');
```

**Comment by seanjohnson08** [comment]
This repo has 2 transforms - one is safer (getset-util).

get-set-replace-all is the unsafe one, as you describe.
